### PR TITLE
Deprecate env-var-writing functions

### LINKED ISSUE #30: Environment setters are unsound (aka Rust env setters are unsound)
We've been tracking down a failure in our CI for a few days and in the end, the culprit was `openssl_probe::init_ssl_cert_env_vars` being called in a thread while other code that used `getenv` for a completely was running in another thread. 

https://github.com/sfackler/rust-native-tls/blob/master/src/imp/openssl.rs#L88

Unfortunately, these particular methods are landmines, and should probably be gated behind an unsafe feature while Rust 2024 is in the process of deprecating the "safe" version of set_env.

This is not a security vuln per-se, but it's certainly a major crash risk in complex code that makes use of any non-rust code. 

What ended up happening for us is this:

 - One thread called `init_ssl_cert_env_vars` indirectly by triggering the first `reqwest` access in a process.
 - A second thread was running Python asyncio, which called into `gettext` to format an unrelated error, which called `getenv("LANGUAGE")`
 - `setenv` triggered a `realloc`, causing the environ to move while it was being scanned by the second thread
 - The second thread ends up reading an invalid pointer and segfaulting, bringing the whole process down

I would strongly encourage:

 - Adding an "unsafe_set_env" feature and gating all environment-setting functions behind this
 - Bumping the version and highly discouraging use of the older versions of the crate (possibly via a dependabot alert or CVE, regardless of the minimal actual security risk)

As a workaround, downstream crates like `rust-native-tls` should probe for paths as strings, and directly configure the SSL contexts with those paths, rather than attempting to set them in the environment directly.

### PR DESCRIPTION
**Pull request by alexcrichton**
Replace them with `unsafe` equivalents with documentation indicating that you probably shouldn't rely on them. Not the best solution but given the age of this crate there's not really a whole lot else that can be done.

Closes #30

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -43,16 +43,45 @@ fn cert_dirs_iter() -> impl Iterator<Item = &'static Path> {
...
     ]
-    .iter().map(Path::new).filter(|p| p.exists())
+    .iter()
+    .map(Path::new)
+    .filter(|p| p.exists())
+}
+
+/// Deprecated as this isn't sound, use [`init_openssl_env_vars`] instead.
+#[doc(hidden)]
+#[deprecated(note = "this function is not safe, use `init_openssl_env_vars` instead")]
```
Comment (eaufavor) [inline src/lib.rs:53]: Nitpicking about the message: it reads like "this function is unsafe, so please use the safe version, `init_openssl_env_vars`".
In reality what it means to say is "This function is not correctly marked as unsafe, use the correct version, `init_openssl_env_vars`, instead"
